name: Create index.py

on:
  push:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Update index.py
        run: |
          python data/create.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index.py
          commit_options: '--no-verify --signoff'